POST http://localhost:8080/transactions
Content-Type: "application/json"

{
  "account_id_from": "2b60c4d6-8865-4bf4-863a-76daf75a6b89",
  "account_id_to": "ad743993-6b77-4b2d-860d-a05d22a2030d",
  "amount": 1.00
}